### ISSUE TITLE
Implementar bootstrap

### ISSUE THREAD

**Issue by JorgeBlanchardCruz** [JorgeBlanchardCruz/FormProyect#1]
Crearemos el diseño de nuestra web implementando bootstrap, que es un framework de Twitter que permite crear interfaces web con CSS y Javascript que adaptan la interfaz dependiendo del tamaño del dispositivo en el que se visualice de forma nativa, es decir, automáticamente se adapta al tamaño de un ordenador o de una Tablet sin que el usuario tenga que hacer nada, esto se denomina diseño adaptativo o Responsive Design.

**Comment by mdbGalvan** [comment]
En el commit [Load base practice, #6](https://github.com/alu0100536591/FormProyect/commit/dce5c6b022a933df1cefe5f84fb98d48155ca064) se ha añadido el diseño inicial que tomará el proyecto. Ya luego, se modificará a razón de las exigencias del proyecto (una podría ser elegir el logo, ...)
