### ISSUE TITLE
Cambiar fondo y logo

### ISSUE THREAD

**Issue by mdbGalvan** [JorgeBlanchardCruz/FormProyect#11]
Se buscará un fondo y logo más apropiado al proyecto. Algo, que tenga que ver con los formularios.
El logo estaría bien que fuera png, para que el fondo lo tome del nuestro (png puede tener fondo transparente).

**Comment by mdbGalvan** [comment]
La imagen sólo es de prueba. Es la más apropiada que vi y que fuera png.

**Comment by alu0100403619** [comment]
Ha quedado muy guapo el diseño de jorge. Pienso que debería quedarse así.
