### ISSUE TITLE
¿Y si en lugar de poner el árbol AST ponemos directamente el código HTML?

### ISSUE THREAD

**Issue by JorgeBlanchardCruz** [JorgeBlanchardCruz/FormProyect#13]

**Comment by alu0100403619** [comment]
A Casiano también le gusta ver el AST

**Comment by JorgeBlanchardCruz** [comment]
Ok, la parte del output la modifiqué para que salga en un futuro el AST y el HTML

**Comment by mdbGalvan** [comment]
Es que estaba pensado para que se viera el AST y FORM. Y en el botón de exportar se pasara el HTML.

**Comment by JorgeBlanchardCruz** [comment]
Ok, me parece genial!
