### ISSUE TITLE
Mejorar la distribución de los elementos visuales de la aplicación web para que resulte más intuitiva y fácil de manejar.

### ISSUE THREAD

**Issue by JorgeBlanchardCruz** [JorgeBlanchardCruz/FormProyect#14]

**Comment by JorgeBlanchardCruz** [comment]
He modificado el index.erb. No sé si os gustará. Sino volvemos a una versión anterior. De todas maneras aún faltan retoques.

**Comment by mdbGalvan** [comment]
A mi me parece genial así. Mucho más intuitivo y fácil de manejar.
