### ISSUE TITLE
BUG - VALUE: no permite vocales acentuadas y caracteres especiales

### ISSUE THREAD

**Issue by JorgeBlanchardCruz** [JorgeBlanchardCruz/FormProyect#18]
Si os parece, vamos escribiendo aquí los bugs que nos vamos encontrando, para tener más fácil acceso:
- Hay un bug con el elemento 'LBL'. Por el formato del output salen con un marco con borde. Debería ser solo texto plano.

**Comment by JorgeBlanchardCruz** [comment]
- Encontrado un bug en el regex de VALUE: No permite vocales acentuadas.

**Comment by JorgeBlanchardCruz** [comment]
- Encontrado un bug en el regex de VALUE: tampoco permite caracteres de especiales como : -,+,!¿? .. y muchos más

**Comment by mdbGalvan** [comment]
A mi parece que estaría mejor:
- Crear un issue por bug.
- Crear un milestone que almacene todos estos bugs que encontremos.

Y creo que esta manera nos será más fácil encontrarlo y solucionarlos.

**Comment by mdbGalvan** [comment]
Lo que hice para que reconociera esos caracteres hice:

```
PATH        = _ (["]) path:$([\/]?[a-zA-Z0-9áéíóú+!\/]*.[a-zA-Z_0-9]*) (["]) _ 
                                                                  { return path; }
VALUE       = _ (["]) val:$([a-zA-Z0-9\-_áéíóú+!. ]*) (["]) _     { return val; }
MAIL        = _ email:$([a-zA-Z_0-9.-áéíóú+!]*[@][a-zA-Z]*.[a-zA-Z]*) _
```

Además, añadí esos caracteres a path y mail.

**Comment by JorgeBlanchardCruz** [comment]
Esto lo puse como bug porque ya anoche estaba muy cansado.
