### ISSUE TITLE
Bug - marco del LBL

### ISSUE THREAD

**Issue by mdbGalvan** [JorgeBlanchardCruz/FormProyect#19]
Hay un bug con el elemento 'LBL'. Por el formato del output salen con un marco con borde. Debería ser solo texto plano.

**Comment by mdbGalvan** [comment]
Tiene borde porque muestra el formato que nosotros tenemos en nuestra página (que está hecho en bootstrap). Es decir, cuando vayamos a exportar el fichero no va a salir este formato, sino el que definamos (que está por ahora en proceso). 

De hecho, pueden copiar en un fichero lo que sale en la columna HTML, y verán como sale el verdadero formato (por cierto, muy feo).

**Comment by JorgeBlanchardCruz** [comment]
Claro, es que sin el CSS quedará feo. Tenemos hasta el lunes para incluirlo.
