### ISSUE TITLE
Diseñar gramática

### ISSUE THREAD

**Issue by JorgeBlanchardCruz** [JorgeBlanchardCruz/FormProyect#2]
Analizar todas las posibilidades que ofrece qrcode.js. Una vez aquí, deberemos especificar que es lo que queremos que realicé nuestro parseo, y escibir una gramática específica para ello.

**Comment by mdbGalvan** [comment]
Tras reunirnos, hemos llegado a la conclusión que el proyecto anterior pensado era complicar algo sencillo. Y se nos ha ocurrido, realizar el proyecto sobre un generador de formularios estándar. Además, hemos definido en papel la futura gramática.
