### ISSUE TITLE
Bug - Table no obliga a EndTable

### ISSUE THREAD

**Issue by mdbGalvan** [JorgeBlanchardCruz/FormProyect#20]
Como está definida la gramática, puede que insertes **TABLE** pero no cerrarlo. 

```
 / t:table             { return t; }
 / e:endtable          { return e; }
```

Debería estar definida dentro de **table**.

```
table = TABLE c:(NUMBER)? w:(NUMBER)? ENDTABLE
```

**Comment by mdbGalvan** [comment]
Funciona para AST, pero en el FORM no sé porque pero la tabla la coge antes. Es algo raro, porque en el ast se ve claramente que dentro de la table están los otros elementos. Es que no me ha dado tiempo de verlo mucho más. Ya seguiré mañana.

**Comment by JorgeBlanchardCruz** [comment]
Me acabo de dar cuenta de que lo puse así 
 / t:table             { return t; }
 / e:endtable          { return e; }
por una razón. El código de las acciones semánticas (entre {...}) se ejecuta después de haber pillado todos los elementos que están dentro de la tabla. Por lo tanto, el programa aún no sabe que está creando una tabla y en consecuencia no pone las etiquetas HTML para ello. 

Este problema, y otros, tuve a la hora de implementar TABLE, ya que no lo quería exactamente como lo dejé. Pero finalmente me decidí por ese que era más sencillo.

Si el usuario quiere dejar de utilizar TABLE que ponga ENDTABLE. Hasta que no lo haga, el programa seguirá identificado como que está creando filas y columnas. Y no es obligado poner ENDTABLE.

Qué os parece?

**Comment by JorgeBlanchardCruz** [comment]
Lo dejaré como estaba antes si os parece bien.

**Comment by JorgeBlanchardCruz** [comment]
Poner ENDTABLE sin haber declarado antes TABLE no tiene mucho sentido, pero no da error HTML.

**Comment by JorgeBlanchardCruz** [comment]
Cierro el tema, ya que le he dado una solución aunque no sea la óptima.
