### ISSUE TITLE
BUG - Sing in de Google+ no funciona.

### ISSUE THREAD

**Issue by JorgeBlanchardCruz** [JorgeBlanchardCruz/FormProyect#23]

**Comment by JorgeBlanchardCruz** [comment]
Cree con mi cuenta la app de heroku formproyect, puede ser eso?

**Comment by mdbGalvan** [comment]
No funciona porque en el **auth.rb** se escoge la local: 

```
provider :google_oauth2, config['identifier_gg_local'], config['secret_gg_local']
```

En vez, de la de heroku:

```
provider :google_oauth2, config['identifier_gg'], config['secret_gg']
```

Lo puse inicialmente así, porque no sabía como era la dirección de nuestro proyecto. Y así poder trabajar en local cómodamente.

Lo cambio, y añado en **config.yml** los datos de la página, que tampoco estaba configurado.

**Comment by mdbGalvan** [comment]
Recordar que en el **rakefile** se tiene la siguiente tarea:

```
desc "Use the filled client_secrets"
task :use_keys do
  sh "cp config/config_filled.yml config/config.yml"
end
```

Y se ejecuta cuando se inicia el **rake**, por lo que, los cambios había que hacerlo en: `config_filled.yml` no en `config.yml`.

**Comment by mdbGalvan** [comment]
Por fin, funciona para gitHub. Pero me falla en github. Voy a mirar el **developers google** creo que puse algo mal en el callback.

**Comment by mdbGalvan** [comment]
El problema creo que es:
- Developers google, piensa que mi correo es el propietario del link. Pero ya lo cambié pero todavía tiene que aceptarme jorge la petición. 
- Sino fuera esto, entonces, mejor que jorge configure el developers en google y cambiara los resultados en config_filled.yml
