### ISSUE TITLE
Subir una práctica que sirva como base

### ISSUE THREAD

**Issue by JorgeBlanchardCruz** [JorgeBlanchardCruz/FormProyect#6]
Para partir de una base, y no tener que realizarlo todo desde el principio. Se ha optado por escoger un retal de prácticas anteriores.

**Comment by mdbGalvan** [comment]
Cargué la base de la práctica a partir de las prácticas 6, 7 y 8. Modificando los datos para ser más personalizado a nuestro proyecto.
