### ISSUE TITLE
Implementar la gramática

### ISSUE THREAD

**Issue by JorgeBlanchardCruz** [JorgeBlanchardCruz/FormProyect#7]
Después de haber tenido definida toda la gramática, se implementará un parseado de ella mediante la librería de javascript, **PGE.js**.

**Comment by mdbGalvan** [comment]
Hemos generado el **AST** de la gramática, a continuación, deberíamos implementar la **salida del formulario** en código _HTML_ y _CSS_. 

Además, en el último commit realizamos:
1. Añadimos una gramática más compleja para el **ejemplo inicial**.
2. Añadimos la salida para obtener el **AST**.
3. Eliminamos la igual en **Logo, width, height** para hacer más sencilla la gramática para el usuario.
4. Añadimos en **VALUE** la posibilidad de poder ingresar **. espacio - _ *_.
5. Y por último, añadimos en el *_PATH** la extensión, ya que antes no la tomama.

**MEJORA**: Habría que hacer que la extesión fuera de un nº limitado de caracteres, pero no lo he encontrado como se hace en PGE.js.

**Comment by JorgeBlanchardCruz** [comment]
Hemos implementado nuevos elementos para el formulario: label, whiteline, line, button.
Se ha mejorado sensiblemente la intuitividad del código de usuario (Las etiquetas de los elementos no son obligatorias y además van entre comillas dobles).
Se puede ordenar de forma más personalizada los elementos del formulario gracias a lines y whitelines.

He modificado la función var form_ = function (typ, lab, nam, val) para que se ajuste más a cada uno de los elementos.

He cambiado la distribución de los objetos en la aplicación Web, intentando que sea más fácil de manejar. Aún queda mucho margen de mejora!!!!!! Espero que les agrade.

**Comment by mdbGalvan** [comment]
Perfecto, muy buen trabajo.

**Comment by JorgeBlanchardCruz** [comment]
Encontrado un bug en el regex de VALUE: No permite vocales acentuadas.

**Comment by JorgeBlanchardCruz** [comment]
WHITELINE es ahora ";" ya que los programadores estamos más familiarizado a esto que a ":".
