### ISSUE TITLE
Crear el formulario

### ISSUE THREAD

**Issue by mdbGalvan** [JorgeBlanchardCruz/FormProyect#8]
Se tendrá que realizar una función que cree el formulario tras leer la gramática.

**Comment by mdbGalvan** [comment]
Se ha implementado la parte del formulario, pero no se ha terminado. 
También, se ha observado que existe un **bug** en **PATH**  **VALUE** en los símbolos de escape.

**Comment by mdbGalvan** [comment]
Hay que hacer que la salida de los datos sea una cadena, debido esta salida será un fichero html.

**Comment by mdbGalvan** [comment]
Se ha creado la `function css` para sacar la salida de las opciones del formulario. Pero está comentada porque da un fallo.

**Comment by mdbGalvan** [comment]
Hay que corregir la función:

```
  var form_ = function (typ, lab, nam, val) {
    var attrid;
    if(typ == "radio")
        attrid = "name"
    else
        attrid = "id"   

    val = val.replace(/\"/g,'');
    var pr = "<p>"+lab+"</p>";
    pr += "<input type='"+typ+"' "+attrid+"='"+nam+"' placeholder='"+val+"'>";
    var po = "</br>"; 
    return pr+po;
  }
```

Porque para algunos elementos como: **radio, checkbox, ... *\* no tienen **placeholder**, pero tiene un **texto** donde se informa del valor a elegir. No sé, personalizarlo mejor.

**Comment by JorgeBlanchardCruz** [comment]
He modificado dicha función para que se ajuste más a cada elemento.
No sé si a lo que te referías con TEXTO está reflejado.

**Comment by mdbGalvan** [comment]
Perfecto, a eso mismo me refería. Y me encantó la nueva distribución.
