### ISSUE TITLE
Crear Botón y función para descargar el formulario

### ISSUE THREAD

**Issue by mdbGalvan** [JorgeBlanchardCruz/FormProyect#9]
Hay que crear un botón y una función para que el usuario pueda exportar su formulario.

**Comment by mdbGalvan** [comment]
Para crear una función en javascript que nos permita la descarga, podríamos hacerlo con **FileWriter**. Una página que está bastante bien es: [FileSystem API's](http://www.html5rocks.com/es/tutorials/file/filesystem/) ó [Gist](https://gist.github.com/greenido/979770).
Encontré una [demo](http://demo.tutorialzine.com/2011/05/generating-files-javascript-php/#) y viene explicado [aquí](http://tutorialzine.com/2011/05/generating-files-javascript-php/).

**Comment by alu0100403619** [comment]
OK, me pongo a ello, que acabo de salir de la charla de practicas y trabajo de fin de grado

**Comment by alu0100403619** [comment]
No me encuentra el php. :8ball:

**Comment by alu0100403619** [comment]
Sigue sin encontrar los ficheros php, aunque están referenciados en el index.erb

**Comment by mdbGalvan** [comment]
Conseguí una manera diferente de hacerlo, con ayuda de esta función:

```
function save(a, filename) {
  var myCodeMirror = $(".CodeMirror")[0].CodeMirror;
  var source = myCodeMirror.getValue();
  var result2 = form.parse(source);
  var content = result2.FORM;


  contentType =  'data:application/octet-stream,';
  uriContent = contentType + encodeURIComponent(content);
  a.setAttribute('href', uriContent);
  a.setAttribute('download', filename);
}
```

**Comment by mdbGalvan** [comment]
Funciona perfectamente, y tiene el formato correcto el botón.
Si se quisiera añadir el botón para que saliera también en pdf podrías ver esta [librería](http://parall.ax/products/jspdf)
